# Generated by Django 6.0.7 on 2026-07-14 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام فروشگاه")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="شناسه یکتا"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shops/logos/",
                        verbose_name="لوگو",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shops/banners/",
                        verbose_name="بنر",
                    ),
                ),
                (
                    "shop_type",
                    models.CharField(
                        choices=[
                            ("social", "فروشنده اجتماعی"),
                            ("hybrid", "فروشگاه\u200cدار هیبریدی"),
                            ("network", "فروشنده تلفنی/شبکه\u200cای"),
                        ],
                        default="social",
                        max_length=15,
                        verbose_name="نوع فروشگاه",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="تلفن تماس"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="آدرس"),
                ),
                (
                    "geo_lat",
                    models.FloatField(
                        blank=True, null=True, verbose_name="عرض جغرافیایی"
                    ),
                ),
                (
                    "geo_lng",
                    models.FloatField(
                        blank=True, null=True, verbose_name="طول جغرافیایی"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shops",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مالک",
                    ),
                ),
            ],
            options={
                "verbose_name": "فروشگاه",
                "verbose_name_plural": "فروشگاه\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="قیمت (تومان)"
                    ),
                ),
                ("stock", models.IntegerField(default=1, verbose_name="موجودی")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/",
                        verbose_name="تصویر اصلی",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "نو"),
                            ("like_new", "در حد نو"),
                            ("used", "کارکرده"),
                            ("needs_repair", "نیاز به تعمیر"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="وضعیت کالا",
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("perfect", "کاملاً سالم"),
                            ("scratched", "خط و خش جزئی"),
                            ("minor_damage", "آسیب جزئی"),
                            ("major_damage", "آسیب جدی"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="وضعیت سلامت",
                    ),
                ),
                (
                    "health_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="توضیحات سلامت"
                    ),
                ),
                (
                    "allow_local_test",
                    models.BooleanField(default=False, verbose_name="امکان تست حضوری"),
                ),
                (
                    "allow_courier",
                    models.BooleanField(
                        default=False, verbose_name="امکان ارسال با پیک"
                    ),
                ),
                (
                    "story",
                    models.TextField(
                        blank=True, null=True, verbose_name="داستان محصول"
                    ),
                ),
                (
                    "buy_link_active",
                    models.BooleanField(default=True, verbose_name="لینک خرید فعال"),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="قابل نمایش"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="shops.shop",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="shop",
            index=models.Index(fields=["slug"], name="shops_shop_slug_f77e23_idx"),
        ),
        migrations.AddIndex(
            model_name="shop",
            index=models.Index(fields=["owner"], name="shops_shop_owner_i_de9788_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["shop"], name="shops_produ_shop_id_2cd91f_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["condition"], name="shops_produ_conditi_ad64cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="shops_produ_price_7c95e3_idx"),
        ),
    ]
