# Generated by Django 6.0.7 on 2026-08-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(
                blank=True, default="", max_length=50, null=True, verbose_name="رنگ"
            ),
        ),
    ]
