# Generated by Django 6.0.7 on 2026-08-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0002_add_color_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="دسته\u200cبندی"
            ),
        ),
    ]
