# Generated by Django 6.1 on 2026-08-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0003_add_category_field_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="colors",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="رنگ\u200cبندی با موجودی"
            ),
        ),
    ]
