# Generated by Django 6.1 on 2026-08-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0004_add_colors_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.JSONField(blank=True, default=dict, verbose_name="سایزبندی"),
        ),
    ]
