# Generated by Django 6.1 on 2026-08-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0005_make_description_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="توضیحات"
            ),
        ),
    ]
