# Generated by Django 6.1 on 2026-09-12 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0006_make_description_optional_v4"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="purchase_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="قیمت خرید",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="warehouse_stock",
            field=models.IntegerField(default=0, verbose_name="موجودی انبار"),
        ),
        migrations.CreateModel(
            name="SellerExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="آیکون"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="مبلغ (تومان)"
                    ),
                ),
                ("expense_date", models.DateField(verbose_name="تاریخ")),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="فروشنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "هزینه جانبی",
                "verbose_name_plural": "هزینه\u200cهای جانبی",
                "ordering": ["-expense_date", "-created_at"],
            },
        ),
    ]
