# Generated by Django 6.1 on 2026-09-26 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0007_add_seller_expense_v2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerDebt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "debt_type",
                    models.CharField(
                        choices=[
                            ("debtor", "بدهکار (طلب من از دیگران)"),
                            ("creditor", "بستانکار (طلب دیگران از من)"),
                        ],
                        max_length=10,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "person_name",
                    models.CharField(max_length=100, verbose_name="نام شخص"),
                ),
                (
                    "person_phone",
                    models.CharField(max_length=15, verbose_name="شماره تماس"),
                ),
                (
                    "person_national_id",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="کد ملی"
                    ),
                ),
                (
                    "person_address",
                    models.TextField(blank=True, default="", verbose_name="آدرس"),
                ),
                (
                    "person_postal_code",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="کد پستی"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="مبلغ (تومان)"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="پرداخت\u200cشده",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ سررسید"
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("cash", "نقدی"),
                            ("check", "چکی"),
                            ("installment", "اقساطی"),
                            ("credit", "نسیه"),
                        ],
                        default="credit",
                        max_length=15,
                        verbose_name="نوع پرداخت",
                    ),
                ),
                (
                    "is_installment",
                    models.BooleanField(default=False, verbose_name="اقساطی"),
                ),
                (
                    "installment_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="تعداد اقساط"
                    ),
                ),
                (
                    "installment_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="مبلغ هر قسط",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="شرح")),
                ("transaction_date", models.DateField(verbose_name="تاریخ تراکنش")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="فروشنده",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="debts",
                        to="shops.shop",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "بدهکار/بستانکار",
                "verbose_name_plural": "بدهکاران و بستانکاران",
                "ordering": ["-transaction_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["seller", "debt_type"],
                        name="shops_selle_seller__c55cbb_idx",
                    ),
                    models.Index(
                        fields=["seller", "person_name"],
                        name="shops_selle_seller__34e23e_idx",
                    ),
                    models.Index(
                        fields=["due_date"], name="shops_selle_due_dat_48431a_idx"
                    ),
                ],
            },
        ),
    ]
