# Generated by Django 6.1 on 2026-09-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0008_sellerexpense_shop_sellerdebt"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerdebt",
            name="card_number",
            field=models.CharField(
                blank=True, default="", max_length=16, verbose_name="شماره کارت"
            ),
        ),
        migrations.AddField(
            model_name="sellerdebt",
            name="sheba_number",
            field=models.CharField(
                blank=True, default="", max_length=26, verbose_name="شماره شبا"
            ),
        ),
    ]
