# Generated by Django 6.1 on 2026-09-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0009_sellerdebt_card_number_sellerdebt_sheba_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerdebt",
            name="bank_name",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="نام بانک"
            ),
        ),
    ]
