#!/bin/bash
echo "========================================="
echo "📊 گزارش کامل فضای کداسپیس"
echo "========================================="
echo ""
echo "📁 فضای کل دیسک:"
df -h /workspaces
echo ""
echo "📂 حجم پروژه:"
du -sh /workspaces/raste-platform 2>/dev/null || echo "پروژه پیدا نشد"
echo ""
echo "🐳 فضای Docker:"
docker system df 2>/dev/null || echo "Docker در دسترس نیست"
echo ""
echo "📦 کش کاربر:"
du -sh /home/codespace/.cache 2>/dev/null || echo "کشی وجود ندارد"
echo ""
echo "🗑️ فایل‌های موقت:"
du -sh /tmp 2>/dev/null || echo "فایل موقتی وجود ندارد"
echo ""
echo "📦 فایل‌های بکاپ:"
ls -lh /workspaces/*.tar.gz 2>/dev/null || echo "هیچ فایل بکاپی وجود ندارد"
echo "========================================="
