# Generated by Django 6.0.7 on 2026-07-15 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("seller", "فروشنده"), ("courier", "پیک")],
                        max_length=10,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "stars",
                    models.IntegerField(
                        choices=[(1, "⭐ معمولی"), (2, "⭐⭐ خوب"), (3, "⭐⭐⭐ عالی")],
                        verbose_name="ستاره",
                    ),
                ),
                ("score", models.IntegerField(verbose_name="امتیاز از ۱۰۰")),
                (
                    "quality_score",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "ضعیف"), (2, "متوسط"), (3, "عالی")],
                        null=True,
                        verbose_name="کیفیت کالا",
                    ),
                ),
                (
                    "speed_score",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "کند"), (2, "معمولی"), (3, "سریع")],
                        null=True,
                        verbose_name="سرعت ارسال",
                    ),
                ),
                (
                    "communication_score",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "ضعیف"), (2, "خوب"), (3, "عالی")],
                        null=True,
                        verbose_name="ارتباط با مشتری",
                    ),
                ),
                (
                    "accuracy_score",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "ندارد"), (2, "متوسط"), (3, "کامل")],
                        null=True,
                        verbose_name="تطابق با توضیحات",
                    ),
                ),
                (
                    "delivery_speed_score",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "کند"), (2, "معمولی"), (3, "سریع")],
                        null=True,
                        verbose_name="سرعت پیک",
                    ),
                ),
                (
                    "behavior_score",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "ضعیف"), (2, "خوب"), (3, "عالی")],
                        null=True,
                        verbose_name="رفتار پیک",
                    ),
                ),
                (
                    "package_health_score",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "آسیب\u200cدیده"),
                            (2, "سالم"),
                            (3, "کاملاً سالم"),
                        ],
                        null=True,
                        verbose_name="سلامت بسته",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="نظر"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "rated_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="دریافت\u200cکننده امتیاز",
                    ),
                ),
                (
                    "rater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="امتیازدهنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "امتیاز عمومی",
                "verbose_name_plural": "امتیازات عمومی",
                "indexes": [
                    models.Index(
                        fields=["rated_user"], name="ratings_pub_rated_u_bdcd2d_idx"
                    ),
                    models.Index(
                        fields=["order"], name="ratings_pub_order_i_270c7b_idx"
                    ),
                ],
                "unique_together": {("rater", "order", "target_type")},
            },
        ),
        migrations.CreateModel(
            name="SellerHiddenRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loyalty_score",
                    models.IntegerField(default=50, verbose_name="وفاداری (۰-۱۰۰)"),
                ),
                (
                    "prompt_payment_score",
                    models.IntegerField(default=50, verbose_name="پرداخت به موقع"),
                ),
                (
                    "low_return_score",
                    models.IntegerField(default=50, verbose_name="مرجوعی کم"),
                ),
                (
                    "referral_score",
                    models.IntegerField(default=50, verbose_name="معرفی به دیگران"),
                ),
                (
                    "total_score",
                    models.IntegerField(default=50, verbose_name="امتیاز کل"),
                ),
                (
                    "seller_note",
                    models.TextField(
                        blank=True, null=True, verbose_name="یادداشت فروشنده"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hidden_ratings_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مشتری",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hidden_ratings_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="فروشنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "امتیاز مخفی",
                "verbose_name_plural": "امتیازات مخفی",
                "unique_together": {("seller", "customer")},
            },
        ),
    ]
