# Generated by Django 6.0.7 on 2026-07-13 16:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=15, verbose_name="شماره تلفن")),
                ("code", models.CharField(max_length=6, verbose_name="کد")),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("register", "ثبت\u200cنام"),
                            ("login", "ورود"),
                            ("order_confirm", "تأیید سفارش"),
                        ],
                        default="register",
                        max_length=20,
                        verbose_name="هدف",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="استفاده شده؟"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="تاریخ انقضا")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "کد تأیید",
                "verbose_name_plural": "کدهای تأیید",
                "indexes": [
                    models.Index(
                        fields=["phone", "purpose"], name="users_otpco_phone_b654dc_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        max_length=15,
                        unique=True,
                        verbose_name="شماره تلفن",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=10,
                        null=True,
                        unique=True,
                        verbose_name="کد ملی",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("buyer", "خریدار"),
                            ("seller", "فروشنده"),
                            ("courier", "پیک"),
                            ("service_provider", "سرویس\u200cدهنده"),
                            ("hybrid", "هیبرید"),
                        ],
                        default="buyer",
                        max_length=20,
                        verbose_name="نوع کاربر",
                    ),
                ),
                (
                    "preferred_contact",
                    models.CharField(
                        choices=[
                            ("sms", "پیامک"),
                            ("eitaa", "ایتا"),
                            ("telegram", "تلگرام"),
                            ("phone_call", "تماس تلفنی"),
                        ],
                        default="sms",
                        max_length=15,
                        verbose_name="روش تماس ترجیحی",
                    ),
                ),
                (
                    "subscription_plan",
                    models.CharField(
                        choices=[
                            ("free", "رایگان"),
                            ("silver", "نقره\u200cای"),
                            ("gold", "طلایی"),
                        ],
                        default="free",
                        max_length=15,
                        verbose_name="پلن اشتراک",
                    ),
                ),
                (
                    "subscription_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ شروع اشتراک"
                    ),
                ),
                (
                    "subscription_expiry",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ پایان اشتراک"
                    ),
                ),
                (
                    "trial_used",
                    models.BooleanField(
                        default=False, verbose_name="دوره آزمایشی استفاده شده؟"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="تصویر پروفایل",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ عضویت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="آخرین به\u200cروزرسانی"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربران",
                "indexes": [
                    models.Index(fields=["phone"], name="users_user_phone_9474e8_idx"),
                    models.Index(
                        fields=["national_id"], name="users_user_nationa_7d24c6_idx"
                    ),
                    models.Index(
                        fields=["user_type"], name="users_user_user_ty_4573bb_idx"
                    ),
                ],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
