# Generated by Django 6.0.7 on 2026-07-17 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="موجودی (تومان)",
                    ),
                ),
                (
                    "frozen_balance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="موجودی مسدود (تومان)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "کیف پول",
                "verbose_name_plural": "کیف پول\u200cها",
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "💰 شارژ کیف پول"),
                            ("withdraw", "🏦 برداشت"),
                            ("sale", "🛍️ درآمد فروش"),
                            ("courier_fee", "🛵 هزینه پیک"),
                            ("courier_income", "🛵 درآمد پیک"),
                            ("refund", "↩️ بازگشت وجه"),
                            ("commission", "📊 کارمزد راسته"),
                            ("subscription", "⭐ شارژ اشتراک"),
                            ("bonus", "🎁 هدیه"),
                        ],
                        max_length=20,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="مبلغ (تومان)"
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        verbose_name="موجودی پس از تراکنش",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="توضیحات"),
                ),
                (
                    "reference_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="شناسه مرجع"
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="نوع مرجع"
                    ),
                ),
                (
                    "is_successful",
                    models.BooleanField(default=True, verbose_name="موفق"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ"),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="users.wallet",
                        verbose_name="کیف پول",
                    ),
                ),
            ],
            options={
                "verbose_name": "تراکنش کیف پول",
                "verbose_name_plural": "تراکنش\u200cهای کیف پول",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["wallet"], name="users_walle_wallet__26b994_idx"
                    ),
                    models.Index(
                        fields=["transaction_type"],
                        name="users_walle_transac_478769_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="users_walle_created_668a18_idx"
                    ),
                ],
            },
        ),
    ]
