# Generated by Django 6.0.7 on 2026-07-17 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_wallet_wallettransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blocked_reason",
            field=models.TextField(blank=True, null=True, verbose_name="دلیل مسدودیت"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_blocked",
            field=models.BooleanField(default=False, verbose_name="مسدود شده؟"),
        ),
        migrations.CreateModel(
            name="AbuseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="شماره تلفن"
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="شناسه دستگاه (FingerprintJS)",
                    ),
                ),
                (
                    "browser_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="شناسه مرورگر (Local Storage)",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="آدرس IP"
                    ),
                ),
                (
                    "geo_location",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="موقعیت جغرافیایی",
                    ),
                ),
                (
                    "risk_score",
                    models.IntegerField(default=0, verbose_name="امتیاز ریسک (۰-۱۰۰)"),
                ),
                (
                    "risk_factors",
                    models.JSONField(default=dict, verbose_name="عوامل ریسک"),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="نوع دستگاه"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "action_taken",
                    models.CharField(
                        choices=[
                            ("flagged", "🚩 پرچم\u200cگذاری"),
                            ("blocked", "🚫 مسدود"),
                            ("verified", "✅ تأیید هویت"),
                            ("allowed", "🟢 مجاز"),
                        ],
                        default="flagged",
                        max_length=20,
                        verbose_name="اقدام",
                    ),
                ),
                (
                    "is_vpn",
                    models.BooleanField(default=False, verbose_name="VPN/Proxy؟"),
                ),
                (
                    "is_emulator",
                    models.BooleanField(default=False, verbose_name="شبیه\u200cساز؟"),
                ),
                (
                    "is_rapid_signup",
                    models.BooleanField(
                        default=False, verbose_name="ثبت\u200cنام سریع؟"
                    ),
                ),
                (
                    "multiple_accounts_count",
                    models.IntegerField(
                        default=0, verbose_name="تعداد حساب\u200cهای مرتبط"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abuse_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ امنیتی",
                "verbose_name_plural": "لاگ\u200cهای امنیتی",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["phone"], name="users_abuse_phone_b361e6_idx"),
                    models.Index(
                        fields=["device_id"], name="users_abuse_device__244237_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="users_abuse_ip_addr_d9be3d_idx"
                    ),
                    models.Index(
                        fields=["risk_score"], name="users_abuse_risk_sc_085cdd_idx"
                    ),
                ],
            },
        ),
    ]
