# Generated by Django 6.0.7 on 2026-07-14 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="کد رهگیری",
                    ),
                ),
                (
                    "customer_guest_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="اطلاعات مشتری مهمان"
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="تعداد")),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="مبلغ کل (تومان)"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("web", "وب"),
                            ("telegram", "تلگرام"),
                            ("eitaa", "ایتا"),
                            ("sms", "پیامک"),
                            ("manual", "دستی (تلفنی)"),
                        ],
                        default="web",
                        max_length=20,
                        verbose_name="منبع سفارش",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_confirmation", "در انتظار تأیید"),
                            ("confirmed", "تأیید شده"),
                            ("packed", "بسته\u200cبندی شده"),
                            ("shipped", "ارسال شده"),
                            ("delivered", "تحویل داده شده"),
                            ("cancelled", "لغو شده"),
                        ],
                        default="pending_confirmation",
                        max_length=25,
                        verbose_name="وضعیت سفارش",
                    ),
                ),
                (
                    "confirmation_code",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="کد تأیید"
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(default=False, verbose_name="تأیید شده؟"),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("online", "آنلاین"),
                            ("cod", "پرداخت در محل"),
                            ("manual", "کارت به کارت"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="روش پرداخت",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("paid", "پرداخت شده"),
                            ("failed", "ناموفق"),
                            ("refunded", "عودت داده شده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت پرداخت",
                    ),
                ),
                (
                    "discount_code_used",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="کد تخفیف استفاده شده",
                    ),
                ),
                (
                    "discount_amount_applied",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="مبلغ تخفیف",
                    ),
                ),
                (
                    "courier_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="هزینه پیک",
                    ),
                ),
                (
                    "shipping_address",
                    models.TextField(blank=True, null=True, verbose_name="آدرس ارسال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "customer_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders_as_customer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مشتری (کاربر)",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="shops.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارشات",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tracking_code"], name="orders_orde_trackin_252782_idx"
                    ),
                    models.Index(
                        fields=["customer_user"], name="orders_orde_custome_cb405a_idx"
                    ),
                    models.Index(
                        fields=["status"], name="orders_orde_status_c6dd84_idx"
                    ),
                    models.Index(
                        fields=["source"], name="orders_orde_source_e5e59d_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="orders_orde_created_0e92de_idx"
                    ),
                ],
            },
        ),
    ]
