# Generated by Django 6.0.7 on 2026-07-17 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerDiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(db_index=True, max_length=50, verbose_name="کد"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("fixed", "💰 مبلغ ثابت"),
                            ("percent", "📊 درصدی"),
                            ("free_shipping", "🚚 ارسال رایگان"),
                        ],
                        max_length=20,
                        verbose_name="نوع تخفیف",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="مقدار تخفیف",
                    ),
                ),
                (
                    "discount_percent",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="درصد تخفیف (حداکثر ۹۹)"
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="حداقل مبلغ سفارش (تومان)",
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="سقف تخفیف (تومان) - برای درصدی",
                    ),
                ),
                (
                    "max_uses",
                    models.IntegerField(default=1, verbose_name="حداکثر تعداد استفاده"),
                ),
                (
                    "used_count",
                    models.IntegerField(default=0, verbose_name="تعداد استفاده شده"),
                ),
                ("valid_from", models.DateTimeField(verbose_name="تاریخ شروع")),
                ("valid_until", models.DateTimeField(verbose_name="تاریخ پایان")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="یادداشت"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="فروشنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "کد تخفیف فروشنده",
                "verbose_name_plural": "کدهای تخفیف فروشندگان",
                "indexes": [
                    models.Index(fields=["code"], name="orders_sell_code_8c7009_idx"),
                    models.Index(
                        fields=["seller"], name="orders_sell_seller__c717a6_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("seller", "code"), name="unique_seller_code"
                    )
                ],
            },
        ),
    ]
