# Generated by Django 6.0.7 on 2026-07-15 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourierPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("motorcycle", "🏍️ موتور"),
                            ("car", "🚗 سواری"),
                            ("pickup", "🚛 وانت"),
                            ("bicycle", "🚲 دوچرخه"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="نوع وسیله",
                    ),
                ),
                (
                    "city_base_fee",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        verbose_name="هزینه پایه درون\u200cشهری (تومان)",
                    ),
                ),
                (
                    "city_per_km_fee",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        verbose_name="هر کیلومتر درون\u200cشهری (تومان)",
                    ),
                ),
                (
                    "suburb_base_fee",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        verbose_name="هزینه پایه حومه (تومان)",
                    ),
                ),
                (
                    "suburb_per_km_fee",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        verbose_name="هر کیلومتر حومه (تومان)",
                    ),
                ),
                (
                    "min_distance_km",
                    models.IntegerField(default=1, verbose_name="حداقل مسافت"),
                ),
                (
                    "max_distance_km",
                    models.IntegerField(default=50, verbose_name="حداکثر مسافت"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "تعرفه پیک",
                "verbose_name_plural": "تعرفه\u200cهای پیک",
            },
        ),
        migrations.CreateModel(
            name="Courier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("motorcycle", "🏍️ موتور"),
                            ("car", "🚗 سواری"),
                            ("pickup", "🚛 وانت"),
                            ("bicycle", "🚲 دوچرخه"),
                        ],
                        max_length=20,
                        verbose_name="نوع وسیله نقلیه",
                    ),
                ),
                (
                    "vehicle_plate",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="شماره پلاک"
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="فعال")),
                (
                    "is_online",
                    models.BooleanField(default=False, verbose_name="آنلاین"),
                ),
                (
                    "current_lat",
                    models.FloatField(
                        blank=True, null=True, verbose_name="موقعیت فعلی (عرض)"
                    ),
                ),
                (
                    "current_lng",
                    models.FloatField(
                        blank=True, null=True, verbose_name="موقعیت فعلی (طول)"
                    ),
                ),
                (
                    "max_distance_km",
                    models.IntegerField(
                        default=10, verbose_name="حداکثر مسافت (کیلومتر)"
                    ),
                ),
                ("rating", models.FloatField(default=5.0, verbose_name="امتیاز")),
                (
                    "total_deliveries",
                    models.IntegerField(default=0, verbose_name="کل ارسال\u200cها"),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار بررسی"),
                            ("documents_uploaded", "مدارک بارگذاری شده"),
                            ("approved", "✅ تأیید شده"),
                            ("rejected", "❌ رد شده"),
                        ],
                        default="pending",
                        max_length=25,
                        verbose_name="وضعیت تأیید",
                    ),
                ),
                (
                    "national_card_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="courier_docs/",
                        verbose_name="تصویر کارت ملی",
                    ),
                ),
                (
                    "license_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="courier_docs/",
                        verbose_name="تصویر گواهینامه",
                    ),
                ),
                (
                    "vehicle_card_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="courier_docs/",
                        verbose_name="تصویر کارت ماشین",
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(
                        blank=True, null=True, verbose_name="یادداشت مدیر"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ تأیید"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ثبت\u200cنام"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_couriers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تأییدکننده",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courier",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیک",
                "verbose_name_plural": "پیک\u200cها",
            },
        ),
        migrations.CreateModel(
            name="CourierRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_address", models.TextField(verbose_name="آدرس فروشنده")),
                ("pickup_lat", models.FloatField(verbose_name="موقعیت فروشنده (عرض)")),
                ("pickup_lng", models.FloatField(verbose_name="موقعیت فروشنده (طول)")),
                ("delivery_address", models.TextField(verbose_name="آدرس مشتری")),
                ("delivery_lat", models.FloatField(verbose_name="موقعیت مشتری (عرض)")),
                ("delivery_lng", models.FloatField(verbose_name="موقعیت مشتری (طول)")),
                ("distance_km", models.FloatField(verbose_name="مسافت (کیلومتر)")),
                (
                    "estimated_fee",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        verbose_name="هزینه پیشنهادی (تومان)",
                    ),
                ),
                (
                    "final_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="هزینه نهایی (تومان)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "منتظر پیک"),
                            ("accepted", "پذیرفته شده"),
                            ("picked_up", "تحویل از فروشنده"),
                            ("in_transit", "در مسیر"),
                            ("delivered", "تحویل به مشتری"),
                            ("cancelled", "لغو"),
                        ],
                        default="pending",
                        max_length=25,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "pickup_code",
                    models.CharField(max_length=4, verbose_name="کد تحویل"),
                ),
                (
                    "delivery_code",
                    models.CharField(max_length=4, verbose_name="کد دریافت"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "courier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="courier.courier",
                        verbose_name="پیک",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courier_request",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courier_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="فروشنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواست پیک",
                "verbose_name_plural": "درخواست\u200cهای پیک",
            },
        ),
    ]
