# Generated by Django 6.0.7 on 2026-07-17 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyaltySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="فعال")),
                (
                    "points_per_1000_toman",
                    models.IntegerField(
                        default=1, verbose_name="امتیاز به ازای هر ۱,۰۰۰ تومان خرید"
                    ),
                ),
                (
                    "first_purchase_bonus",
                    models.IntegerField(default=50, verbose_name="امتیاز اولین خرید"),
                ),
                (
                    "referral_bonus",
                    models.IntegerField(default=100, verbose_name="امتیاز معرفی دوست"),
                ),
                (
                    "birthday_bonus",
                    models.IntegerField(default=200, verbose_name="امتیاز تولد"),
                ),
                (
                    "high_value_bonus",
                    models.IntegerField(default=0, verbose_name="امتیاز خرید ویژه"),
                ),
                (
                    "high_value_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="آستانه خرید ویژه (تومان)",
                    ),
                ),
                (
                    "points_to_credit_rate",
                    models.IntegerField(
                        default=10, verbose_name="نرخ تبدیل (هر ۱۰ امتیاز = ۱ تومان)"
                    ),
                ),
                (
                    "free_shipping_points",
                    models.IntegerField(
                        default=500, verbose_name="امتیاز لازم برای ارسال رایگان"
                    ),
                ),
                (
                    "min_redeem_points",
                    models.IntegerField(
                        default=100, verbose_name="حداقل امتیاز قابل مصرف"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seller",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="فروشنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات باشگاه",
                "verbose_name_plural": "تنظیمات باشگاه\u200cها",
            },
        ),
        migrations.CreateModel(
            name="LoyaltyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("earn", "➕ کسب امتیاز"),
                            ("redeem", "➖ مصرف امتیاز"),
                            ("expire", "❌ انقضا"),
                            ("bonus", "🎁 جایزه"),
                            ("referral", "👥 معرفی"),
                            ("birthday", "🎂 تولد"),
                        ],
                        max_length=20,
                        verbose_name="نوع",
                    ),
                ),
                ("points", models.IntegerField(verbose_name="امتیاز")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="توضیحات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مشتری",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_transactions_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="فروشنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "تراکنش امتیاز",
                "verbose_name_plural": "تراکنش\u200cهای امتیاز",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerLoyaltyPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_points_earned",
                    models.IntegerField(
                        default=0, verbose_name="کل امتیاز کسب\u200cشده"
                    ),
                ),
                (
                    "available_points",
                    models.IntegerField(default=0, verbose_name="امتیاز قابل مصرف"),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("bronze", "🥉 برنزی"),
                            ("silver", "🥈 نقره\u200cای"),
                            ("gold", "🥇 طلایی"),
                            ("platinum", "💎 پلاتینیوم"),
                        ],
                        default="bronze",
                        max_length=20,
                        verbose_name="رتبه",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_points",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مشتری",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_loyalty_points",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="فروشنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "امتیاز مشتری",
                "verbose_name_plural": "امتیازات مشتریان",
                "indexes": [
                    models.Index(
                        fields=["customer", "seller"],
                        name="loyalty_cus_custome_19a925_idx",
                    ),
                    models.Index(fields=["tier"], name="loyalty_cus_tier_4fc0c9_idx"),
                ],
                "unique_together": {("customer", "seller")},
            },
        ),
    ]
