# Generated by Django 6.0.7 on 2026-07-15 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین پیام"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_rooms",
                        to="orders.order",
                        verbose_name="سفارش مرتبط",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="chat_rooms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="شرکت\u200cکنندگان",
                    ),
                ),
            ],
            options={
                "verbose_name": "اتاق گفتگو",
                "verbose_name_plural": "اتاق\u200cهای گفتگو",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "📝 متن"),
                            ("image", "🖼️ تصویر"),
                            ("product", "🛍️ محصول"),
                            ("location", "📍 موقعیت"),
                            ("order", "📦 سفارش"),
                        ],
                        default="text",
                        max_length=15,
                        verbose_name="نوع پیام",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="متن پیام"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="chat/%Y/%m/",
                        verbose_name="فایل پیوست",
                    ),
                ),
                (
                    "reference_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="شناسه مرجع"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="خوانده شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ارسال"),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="فرستنده",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatroom",
                        verbose_name="اتاق",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیام",
                "verbose_name_plural": "پیام\u200cها",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["room", "created_at"],
                        name="chat_chatme_room_id_466ea2_idx",
                    ),
                    models.Index(
                        fields=["sender"], name="chat_chatme_sender__3a9411_idx"
                    ),
                ],
            },
        ),
    ]
