# Generated by Django 6.0.7 on 2026-07-15 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupDeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="deals/", verbose_name="تصویر"
                    ),
                ),
                (
                    "market_price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        verbose_name="قیمت تک در بازار (تومان)",
                    ),
                ),
                (
                    "wholesale_price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        verbose_name="قیمت عمده (تومان)",
                    ),
                ),
                ("min_participants", models.IntegerField(verbose_name="حداقل نفرات")),
                (
                    "current_participants",
                    models.IntegerField(default=0, verbose_name="تعداد فعلی"),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("full", "کل مبلغ"), ("deposit", "بیعانه")],
                        default="full",
                        max_length=20,
                        verbose_name="نوع پرداخت",
                    ),
                ),
                (
                    "deposit_percent",
                    models.IntegerField(default=30, verbose_name="درصد بیعانه"),
                ),
                ("deadline", models.DateTimeField(verbose_name="مهلت ثبت\u200cنام")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "فعال"),
                            ("completed", "تکمیل شده - در انتظار خرید"),
                            ("cancelled", "لغو - تعداد نرسید"),
                            ("closed", "بسته شده - تحویل انجام شد"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="شناسه یکتا")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "deal_maker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="واسط خرید",
                    ),
                ),
            ],
            options={
                "verbose_name": "هم\u200cخرید",
                "verbose_name_plural": "هم\u200cخریدها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupDealParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="نام مهمان"
                    ),
                ),
                (
                    "guest_phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="شماره مهمان"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار پرداخت"),
                            ("paid", "پرداخت شده"),
                            ("refunded", "عودت داده شده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت پرداخت",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        verbose_name="مبلغ پرداختی (تومان)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ثبت\u200cنام"
                    ),
                ),
                (
                    "group_deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="deals.groupdeal",
                        verbose_name="هم\u200cخرید",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "شرکت\u200cکننده",
                "verbose_name_plural": "شرکت\u200cکنندگان",
            },
        ),
        migrations.AddIndex(
            model_name="groupdeal",
            index=models.Index(fields=["slug"], name="deals_group_slug_718a41_idx"),
        ),
        migrations.AddIndex(
            model_name="groupdeal",
            index=models.Index(fields=["status"], name="deals_group_status_11a488_idx"),
        ),
        migrations.AddIndex(
            model_name="groupdeal",
            index=models.Index(
                fields=["deadline"], name="deals_group_deadlin_5812ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupdealparticipant",
            index=models.Index(
                fields=["group_deal"], name="deals_group_group_d_c98810_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupdealparticipant",
            index=models.Index(
                fields=["guest_phone"], name="deals_group_guest_p_f5f06b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="groupdealparticipant",
            unique_together={("group_deal", "guest_phone")},
        ),
    ]
